// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protos/nodeComm.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protos_nodeComm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nodeComm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protos_nodeComm_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Float struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float32                `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Float) Reset() {
	*x = Float{}
	mi := &file_protos_nodeComm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float) ProtoMessage() {}

func (x *Float) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nodeComm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float.ProtoReflect.Descriptor instead.
func (*Float) Descriptor() ([]byte, []int) {
	return file_protos_nodeComm_proto_rawDescGZIP(), []int{1}
}

func (x *Float) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_protos_nodeComm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nodeComm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_protos_nodeComm_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protos_nodeComm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nodeComm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_nodeComm_proto_rawDescGZIP(), []int{3}
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	KeyType       string                 `protobuf:"bytes,3,opt,name=keyType,proto3" json:"keyType,omitempty"`
	ValueType     string                 `protobuf:"bytes,4,opt,name=valueType,proto3" json:"valueType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_protos_nodeComm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nodeComm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_protos_nodeComm_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Data) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Data) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *Data) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type Rebalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Start         uint64                 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rebalance) Reset() {
	*x = Rebalance{}
	mi := &file_protos_nodeComm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rebalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rebalance) ProtoMessage() {}

func (x *Rebalance) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nodeComm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rebalance.ProtoReflect.Descriptor instead.
func (*Rebalance) Descriptor() ([]byte, []int) {
	return file_protos_nodeComm_proto_rawDescGZIP(), []int{5}
}

func (x *Rebalance) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Rebalance) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Rebalance) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

type DataStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	SourceIp      string                 `protobuf:"bytes,3,opt,name=sourceIp,proto3" json:"sourceIp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataStreamReq) Reset() {
	*x = DataStreamReq{}
	mi := &file_protos_nodeComm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStreamReq) ProtoMessage() {}

func (x *DataStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nodeComm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStreamReq.ProtoReflect.Descriptor instead.
func (*DataStreamReq) Descriptor() ([]byte, []int) {
	return file_protos_nodeComm_proto_rawDescGZIP(), []int{6}
}

func (x *DataStreamReq) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *DataStreamReq) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *DataStreamReq) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

var File_protos_nodeComm_proto protoreflect.FileDescriptor

const file_protos_nodeComm_proto_rawDesc = "" +
	"\n" +
	"\x15protos/nodeComm.proto\x12\x06protos\"/\n" +
	"\aRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x1d\n" +
	"\x05Float\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x02R\x05value\"\x1d\n" +
	"\x05Value\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\a\n" +
	"\x05Empty\"f\n" +
	"\x04Data\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\akeyType\x18\x03 \x01(\tR\akeyType\x12\x1c\n" +
	"\tvalueType\x18\x04 \x01(\tR\tvalueType\"C\n" +
	"\tRebalance\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x04R\x03end\"S\n" +
	"\rDataStreamReq\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\x12\x1a\n" +
	"\bsourceIp\x18\x03 \x01(\tR\bsourceIp2\xbf\x02\n" +
	"\x04Node\x12'\n" +
	"\x03Get\x12\x0f.protos.Request\x1a\r.protos.Value\"\x00\x12)\n" +
	"\x05Erase\x12\x0f.protos.Request\x1a\r.protos.Empty\"\x00\x12(\n" +
	"\x06RamUse\x12\r.protos.Empty\x1a\r.protos.Float\"\x00\x12(\n" +
	"\x06CpuUse\x12\r.protos.Empty\x1a\r.protos.Float\"\x00\x12&\n" +
	"\x05Write\x12\f.protos.Data\x1a\r.protos.Empty\"\x00\x122\n" +
	"\fInitiateMove\x12\x11.protos.Rebalance\x1a\r.protos.Empty\"\x00\x123\n" +
	"\bMoveData\x12\x15.protos.DataStreamReq\x1a\f.protos.Data\"\x000\x01B'Z%github.com/utterwqlnut/utterdb/protosb\x06proto3"

var (
	file_protos_nodeComm_proto_rawDescOnce sync.Once
	file_protos_nodeComm_proto_rawDescData []byte
)

func file_protos_nodeComm_proto_rawDescGZIP() []byte {
	file_protos_nodeComm_proto_rawDescOnce.Do(func() {
		file_protos_nodeComm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_nodeComm_proto_rawDesc), len(file_protos_nodeComm_proto_rawDesc)))
	})
	return file_protos_nodeComm_proto_rawDescData
}

var file_protos_nodeComm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_nodeComm_proto_goTypes = []any{
	(*Request)(nil),       // 0: protos.Request
	(*Float)(nil),         // 1: protos.Float
	(*Value)(nil),         // 2: protos.Value
	(*Empty)(nil),         // 3: protos.Empty
	(*Data)(nil),          // 4: protos.Data
	(*Rebalance)(nil),     // 5: protos.Rebalance
	(*DataStreamReq)(nil), // 6: protos.DataStreamReq
}
var file_protos_nodeComm_proto_depIdxs = []int32{
	0, // 0: protos.Node.Get:input_type -> protos.Request
	0, // 1: protos.Node.Erase:input_type -> protos.Request
	3, // 2: protos.Node.RamUse:input_type -> protos.Empty
	3, // 3: protos.Node.CpuUse:input_type -> protos.Empty
	4, // 4: protos.Node.Write:input_type -> protos.Data
	5, // 5: protos.Node.InitiateMove:input_type -> protos.Rebalance
	6, // 6: protos.Node.MoveData:input_type -> protos.DataStreamReq
	2, // 7: protos.Node.Get:output_type -> protos.Value
	3, // 8: protos.Node.Erase:output_type -> protos.Empty
	1, // 9: protos.Node.RamUse:output_type -> protos.Float
	1, // 10: protos.Node.CpuUse:output_type -> protos.Float
	3, // 11: protos.Node.Write:output_type -> protos.Empty
	3, // 12: protos.Node.InitiateMove:output_type -> protos.Empty
	4, // 13: protos.Node.MoveData:output_type -> protos.Data
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_nodeComm_proto_init() }
func file_protos_nodeComm_proto_init() {
	if File_protos_nodeComm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_nodeComm_proto_rawDesc), len(file_protos_nodeComm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_nodeComm_proto_goTypes,
		DependencyIndexes: file_protos_nodeComm_proto_depIdxs,
		MessageInfos:      file_protos_nodeComm_proto_msgTypes,
	}.Build()
	File_protos_nodeComm_proto = out.File
	file_protos_nodeComm_proto_goTypes = nil
	file_protos_nodeComm_proto_depIdxs = nil
}
